#!/usr/bin/env python
# -*- coding: utf-8 -*-
import re
import sys
from dotdotsym.tree import _dot_reference
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(_dot_reference())
